name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn joblib

      - name: Train model
        run: python train_model.py

      - name: Create release file
        run: |
          mkdir output
          mv linear_model.pkl output/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          files: output/linear_model.pkl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
